name: Trigger auto deployment for ironpdf

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/ironpdf-AutoDeployTrigger-5a6b45b3-a69c-418f-b698-e31c4b5804ab.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.IRONPDF_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.IRONPDF_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.IRONPDF_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ./
          dockerfilePath: ./Dockerfile
          registryUrl: crpocs.azurecr.io
          registryUsername: ${{ secrets.IRONPDF_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.IRONPDF_REGISTRY_PASSWORD }}
          containerAppName: ironpdf
          resourceGroup: pocs
          imageToBuild: crpocs.azurecr.io/ironpdf:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


